### ISSUE TITLE
my node is not working

### ISSUE THREAD

**Issue by Jugnu1100** [shardeum/bug-reporting#705]
##### What is the issue?
I update my nodes as discussion in group and now my dashboard is not open.
![shardeum node issue 1](https://github.com/shardeum/shardeum-bug-reporting/assets/159072976/d29e4b46-3fda-4d36-8ec3-54755be04138)

:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by mitia82** [comment]
i have the same crap

**Comment by Jugnu1100** [comment]
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
after run the above command the error coming below ss for your ref

![err1](https://github.com/shardeum/shardeum-bug-reporting/assets/159072976/529ac52d-ad2e-4eeb-a36e-c2058d98c7ba)
![err2](https://github.com/shardeum/shardeum-bug-reporting/assets/159072976/3bd1eba8-c560-445a-8358-cb3201ecb299)
![err3](https://github.com/shardeum/shardeum-bug-reporting/assets/159072976/1f15187c-b70c-4812-bb36-720feaf8151c)
![err4](https://github.com/shardeum/shardeum-bug-reporting/assets/159072976/211f7479-e7fd-4ec4-8cb4-622e5fe22865)
![err5](https://github.com/shardeum/shardeum-bug-reporting/assets/159072976/176f0fea-9bc6-4dd8-ab6d-313659e2b465)
